### ISSUE TITLE
Get list of player names

### ISSUE THREAD

**Issue by InfernalPlacebo** [Yepoleb/python-a2s#1]
Hi, I am trying to get a list of just the player names but I am struggling doing this. I know it is simple to do and I am just overlooking something simple. Previously I used the following code: `

                # Creates the string of player names used in the embed
                for player in server.players()["players"]:
                    if player["name"]:
                        players.append(player["name"])
                player_count = len(players)
                players = ('\n'.join(map(str, players)))` 

I've tried just about every variation of this with the new a2s module and can't get just a list of players without the index, score, and duration as well. Can you help point me to what I am missing?

**Comment by InfernalPlacebo** [comment]
I figured it out:
```players = a2s.players(address)
player_names = []
for player in players:
    player_names.append(player.name)
player_names = ("\n".join(map(str, player_names)))
print(player_names)```

**Comment by Yepoleb** [comment]
This is shorter:
```py
players = a2s.players(server)
player_names = "\n".join(player.name for player in players)
```
