### ISSUE TITLE
Server online at Steam but timed out using this library

### ISSUE THREAD

**Issue by Nereg** [Yepoleb/python-a2s#11]
Hi! I wanted to fetch info about server using your library (version 1.1.5 not async) and it timed out. But when I checkd server in steam it was online ! [Here](https://prnt.sc/th21xw) is link to screenshot. And here is my code:
```python
import a2s
import arrow
import json
ip = "185.189.255.49"
port = 29036
address = (ip, port)
server = a2s.info(address)
players = a2s.players(address)
data = a2s.rules(address)
...
```
And I wonder if this is can be solved with increased timeout value if I will find out how to change it.

**Comment by Nereg** [comment]
No. Longer timeout time does not fix this. I edited [defaults.py](https://github.com/Yepoleb/python-a2s/blob/master/a2s/defaults.py) like this :
```
DEFAULT_TIMEOUT = 10.0
DEFAULT_ENCODING = "utf-8"
DEFAULT_RETRIES = 50
```
And it still timeouts.

**Comment by Yepoleb** [comment]
Some games have a different query port than the game port displayed in the Steam browser. In this case I found it by just trying the port you gave and adding and subtracting 1 and getting a hit at 29035. Adding the server in Steam also only works with 29035, even though it shows 29036 after querying. This is not a bug with this library in my opinion, it's just Steam giving you misleading information.
