### ISSUE TITLE
Fantom players

### ISSUE THREAD

**Issue by Nereg** [Yepoleb/python-a2s#12]
Hi one more time ! When I get list of players I encounter some players that isn't there. Here is [screenshot](https://prnt.sc/tt2vkx). Theare are on list of players when getting it with your library but not there when getting it with steam. Also I attached to your logger so [here](https://pastebin.com/M6Qg2P9N) is what logs look like. I don't know if it is happening with other servers or just with ARK servers. May be I can fix it without editing library.

**Comment by Nereg** [comment]
But maybe it is problemm of ARK not of library. Because I dumped logs to file and analysed it with hex editor. And according to [valve's](https://developer.valvesoftware.com/wiki/Server_queries) and official [wiki](https://ark.gamepedia.com/Server_Browser) description everything is right and that player really exist. But if steam using same protocol and parses it same how it can be ? [Here](https://dropmefiles.com/V9Y1m) is file that I dumped btw

**Comment by Nereg** [comment]
What a pity that I didn't found any programs that are using your library to fetch data about ARK servers

**Comment by Nereg** [comment]
What the heck. Steam is reporting 17 players when in it's own players list I counted only 14 ! I thinks swearing here is not allowed so I will end comment here.

**Comment by Yepoleb** [comment]
This is an unfortunate compromise between accurately parsing the protocol and matching the Steam behavior. In this case I decided to be accurate to the protocol and leave filtering garbage data to the application, as what constitutes garbage data strongly depends on the type of application.

**Comment by Nereg** [comment]
Yeah I don't blame you. You followed protocol definition and it is not your fault. So I just want that behaviour to be documented to help future users.

**Comment by Yepoleb** [comment]
Alright, I already planned to go through past issues and put notes in the readme.

**Comment by Yepoleb** [comment]
Forgot to mention that this got added in https://github.com/Yepoleb/python-a2s/commit/aa418c9e8d1f479384d3e991fc9647957f8b46cf
