### ISSUE TITLE
Different error with async version of library.

### ISSUE THREAD

**Issue by Nereg** [Yepoleb/python-a2s#13]
Hi! I was poking around async version of library and when server is offline there are different error not `socket.timeout`. Here is my traceback :
```
>>> newfeature = asyncio.get_event_loop().run_until_complete(test.AGetInfo())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/app/src/classes.py", line 37, in AGetInfo
    server = await a2s.ainfo((self.address,self.port)) # get server data
  File "/usr/local/lib/python3.7/site-packages/a2s/info.py", line 277, in ainfo
    resp_data = await conn.request(b"\x54Source Engine Query\0")
  File "/usr/local/lib/python3.7/site-packages/a2s/a2sasync.py", line 92, in request
    return await self.recv()
  File "/usr/local/lib/python3.7/site-packages/a2s/a2sasync.py", line 86, in recv
    raise asyncio.TimeoutError()
concurrent.futures._base.TimeoutError
```
Plase add this to [README](https://github.com/Yepoleb/python-a2s/blob/master/README.md) Also I don't use addresses but there would be different error in DNS name resolution too

**Comment by Yepoleb** [comment]
Thanks for the suggestion. Tbh I knew I should do this but got lazy and hoped nobody would notice, but you kinda screwed up my plan. :wink:

**Comment by Nereg** [comment]
Lol yeah I use this library a lot in my project. BTW thank you for such good library and support.

**Comment by Yepoleb** [comment]
This is not fixed, please leave the issue open. I just haven't had time to get to it.

**Comment by Nereg** [comment]
No I just wrongly reopened it. Thanks!

**Comment by Yepoleb** [comment]
I want to fix this and if the issue is closed I may forget, so please leave it open.

**Comment by Yepoleb** [comment]
Now it's ready to be closed :smile:.
