### ISSUE TITLE
Incorrect player_count/max_players response.

### ISSUE THREAD

**Issue by intnx** [Yepoleb/python-a2s#2]
On specific IPs, the info and players responses seem to be off.
Examples: `192.223.30.9:28070`, `177.54.150.18:28015` `139.99.144.50:28009`

When I make a request, and the player count is over 255, it messes things up for some reason.
For example, the players response is capped at 255, and player_count and max_players is off by -255.

Note, these 3 examples are from the same organization, so it could potentially be on their side.

**Comment by Yepoleb** [comment]
Those values are only 8 bits in size, any value above 255 is inevitably going to mess things up. I don't think that's a problem with this particular implementation, the Steam server browser gets confused as well.
