### ISSUE TITLE
Is 255 limit on a2s.player or only on a2s.info ?

### ISSUE THREAD

**Issue by plosnaceruzia** [Yepoleb/python-a2s#24]
At https://www.battlemetrics.com/servers/rust they have more than 255 players - names - stats and I can get max 255 using a2s.player. (Game RUST)

**Comment by Yepoleb** [comment]
It's for both. The BattleMetrics site probably uses a server plugin to get more accurate data.

**Comment by Yepoleb** [comment]
Just checked again, looks like they use RCON https://www.battlemetrics.com/subscription/rcon

**Comment by plosnaceruzia** [comment]
![image](https://user-images.githubusercontent.com/40205675/104436509-fc811600-558d-11eb-85ec-6a12124c9434.png)
some servers do not use their rcon and they track every player
There they have 300+ ppl with time:
![Screenshot_2021-01-13 13 01 Rusty AU NZ Uber 5X LootPlus Kits TP Events QuickSmelt - BattleMetrics](https://user-images.githubusercontent.com/40205675/104436923-7b764e80-558e-11eb-8f74-64106bdd0d0c.jpg)




------------------------
server with rcon:
![image](https://user-images.githubusercontent.com/40205675/104437050-9e086780-558e-11eb-813c-3699ca138832.png)

**Comment by plosnaceruzia** [comment]
Or is there a way to get people list from lowest to the highest number - duration?

**Comment by Yepoleb** [comment]
Looks like at least the player numbers are sent in the server tags as `mp___` and ´cp___`, but I could not figure out how the players are queried. Whatever Rust is doing is nonstandard and I don't really want to research it at the moment.

**Comment by plosnaceruzia** [comment]
![image](https://user-images.githubusercontent.com/40205675/104630202-c5e4f180-569a-11eb-9b05-7675b40e0580.png)
red - qued
yellow - online - connected players
pink - max players

I still do not know how battlemetrics get players from the lowest play duration.

**Comment by plosnaceruzia** [comment]
![image](https://user-images.githubusercontent.com/40205675/104633186-13635d80-569f-11eb-9909-78337747bb84.png)
I can not get anything newer than 255. player duration

and they have a looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooot lower duration

![image](https://user-images.githubusercontent.com/40205675/104633321-4279cf00-569f-11eb-9afc-9212792610bc.png)

**Comment by plosnaceruzia** [comment]
btw thx

**Comment by plosnaceruzia** [comment]
You were right the current server use BM rcon thank you for your time.
