### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by sanderbrw** [Yepoleb/python-a2s#25]
Hi,

I try to run a simple example but I always get a timeout

```
import a2s

print("START")
address = ("85.190.148.87", 7779)
a2s.info(address)
```

```
packet = self._socket.recv(65535) 
socket.timeout: timed out
```

**Comment by Yepoleb** [comment]
Can you query the server with the Steam server browser?

**Comment by Nereg** [comment]
And also `7779` is a game port not query port that the library requires. You can get the query port using simple HTTP API. [Here](https://github.com/Yepoleb/python-a2s#notes) you can find the details.
P.S. Ip `85.190.148.87:27017` works
