### ISSUE TITLE
TF2 Valve server queries timing out

### ISSUE THREAD

**Issue by Kataiser** [Yepoleb/python-a2s#29]
Both a2s.info() and a2s.players() hang until timeout with seemingly all in-use Valve TF2 servers. Community servers still work fine, and old Valve server IPs I still have laying around *technically* work (I can still read server name and such), but any server I'd connected to in-game times out 100% of the time.

Examples:
- `169.254.225.11`, port `18384`: yields [this traceback](https://pastebin.com/WH3AcnvR) after a 2 second timeout. Taking a look at the [Steam servers API](https://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=169.254.225.11), there is definitely a running server there, as well as at a different port. This error also happens: at a longer timeout, when directly calling a2.info() from a REPL, when calling a2s.players(), and when outside of an IDE.
- `169.254.25.245`, port `13512`: same traceback. [Steam API](https://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=169.254.25.245) says only one game server here.
- `162.254.192.155`, port `27053`: this is a counterexample, in that it kind of works but also is an older IP address. [Steam API](https://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=162.254.192.155) says there are actually no servers there, but interestingly, when I just tested it I got [these responses](https://pastebin.com/NCRXyYEp) which have 6/6 players in MvM (it had been 0 players when I tested it in the past).
- `192.223.26.238`, port `27017`: this is a LazyPurple server, which like all community servers I tested, works as expected.

This has been happening for several weeks, with every single server I've joined, but I only just got around to documenting and reporting it. Oddly, python-a2s is a crucial part of my program TF2 Rich Presence, but none of my users have reported any issues so I'm wondering if it's just me or something. I'm also not entirely convinced it's a bug in this library, but idk what else it could be. Python 3.10.2 32-bit, Windows 10 21H2

**Comment by Kataiser** [comment]
Also thank you for this library it's very useful

**Comment by Yepoleb** [comment]
The IP range 192.254.0.0/16 is reserved for link-local use, see [Link-local address](https://en.wikipedia.org/wiki/Link-local_address). They are not routed on the public internet and there is no way you will ever be able to query them, unless you run your own servers at these addresses in your local network. I don't know how these IPs ended up in the Steam API or how you were connecting to them, but you either have some very weird networking stuff going on or your source of data is unfortunately giving you garbage. Thanks for your thorough issue report, I hope I was able to help.

**Comment by Kataiser** [comment]
Ah okay, I'm not very experienced with networking stuff. I'm just getting the IP address from the game console, so no idea what's going wrong. Is there any way I can redirect this to an actual server somehow? And not to mention that last server which seems to work just fine (from my end anyway). Maybe it is something weird here, I've had a lot of router issues for a couple months, which might coincide with this issue.

```
[ReliableMsg] AcceptLobbyInvite successfully sent for Lobby ID 567284810802936 / Abandoning Match 0000000000000000
Connecting to matchmaking server 169.254.225.11:18384
Connecting to 169.254.225.11:18384
Network: IP 192.168.1.183, mode MP, dedicated No, ports 27015 SV / 27005 CL
Connecting to matchmaking server 169.254.225.11:18384
Connecting to 169.254.225.11:18384
Connecting to 169.254.225.11:18384...
[SteamNetworkingSockets] WARNING: Waited 5.0ms for SteamNetworkingSockets lock [ServiceThread]
[SteamNetworkingSockets] WARNING: SteamNetworkingSockets lock held for 15.9ms.  (Performance warning.)  ServiceThread,CProcessP2PSignalFromSteamBackend,InternalReceivedP2PSignal,P2P::ProcessSignal,P2P DestroyICENow,DestroyAllSessions,BRecvCryptoHandshake,BFinishCryptoHandshake(x2)
This is usually a symptom of a general performance problem such as thread starvation.
Connected to 169.254.225.11:18384
Lobby updated

**Comment by Yepoleb** [comment]
The last two servers works, the first two don't. That's how I understood and confirmed it. I don't know why you get garbage IPs and I have no idea how to fix it.

**Comment by Kataiser** [comment]
Alright, thanks for taking a look then

**Comment by WyattRichartz** [comment]
I know this is an old thread but I thought I'd add for anyone else who also comes across this problem:

When you are querying all Team Fortress 2 servers (or all Valve servers for that matter, I'm just using TF2 as an example), you will get information for all servers that are up, whether or not they are a part of a Casual/queue gamemode (e.g. ran directly by Valve) or if they are a private community server. Servers that are in the Casual gamemode are ran directly by Valve in which you cannot choose your individual Casual server. You simply put yourself into a queue and the TF2 game itself puts you into a random Casual server for you to play in. The community servers, however, are a part of a server browser where independent parties can open their own server for people to play on. Thus, these servers are not ran directly by Valve and you can choose exactly what server you would like to join.

Servers that are ran directly by Valve (such as the ones in the Casual gamemode) do not support operations using the a2s protocol such as "a2s.players()," and thus whenever you try to do this on a Valve-run server, you will get a Timeout error. However, when you try using "a2s.players()" on a community server (i.e. one that is not run directly by Valve and one that you can join directly without putting yourself into a queue like in the Casual gamemode), you do get a response. So, from the looks of it, the first 2 ips that you provided are Valve servers that you cannot directly join and thus you cannot get information such as player data from, whereas the bottom 2 ips that you provided are community servers where you can view information such as player lists from. For instance, whenever you click on a community server in the server browser in TF2, you can see the names of the players and the amount of time that they have spent on the server, even without directly connecting to the server. Thus, it makes sense as to how you would be unable to do such a thing on a Valve server that you cannot directly join.

I apologize for the long-winded response, but I've been stuck on this problem myself for ~2 hours or so and I thought I should help anyone else who also comes across a similar problem. And hopefully this helps you and your understanding of why you were coming across this error (if God-forbid you are still working around this problem after over a year and a half of originally asking it...). I hope this makes a bit more sense!

**Comment by Kataiser** [comment]
Yep, pretty much stuff I already knew. The issue was that Valve servers used to work, but no longer do, very possibly because of the new relay system thing.
