### ISSUE TITLE
Example server is down :frowning: 

### ISSUE THREAD

**Issue by Yepoleb** [Yepoleb/python-a2s#31]
Find new example server to use.

**Comment by Nereg** [comment]
You can find many servers for different games here https://www.battlemetrics.com. Found an official [one](https://www.battlemetrics.com/servers/ark/15686334) for ARK. `46.251.238.245:27037` IP + Query port
Has great uptime according to that website. 
Also we can include [this](https://www.battlemetrics.com/servers/csgo/16085516) CS:GO server: `185.248.102.228:30319` (IDK if this is query port)
P.S. Fixed that in #33 and added a note that the server may be down by the time they read it,

**Comment by Yepoleb** [comment]
New server added!
