### ISSUE TITLE
a2s.players name doesn't work for "7 Days to Die"

### ISSUE THREAD

**Issue by Pokihead** [Yepoleb/python-a2s#34]
Like the Title says a2s.info and a2s.rules just work fine.
But a2s.player gives an list of players in which name is always an empty string and index and score is always 0
only duration seems to be working.

**Comment by Yepoleb** [comment]
That's the server returning bad data, I can't do anything about that.

**Comment by Pokihead** [comment]
ok so the 7 Days to Die developers have to fix it?

**Comment by Yepoleb** [comment]
Yes

**Comment by Pokihead** [comment]
Thanks a lot :)
