### ISSUE TITLE
Is it possible to query every server ?

### ISSUE THREAD

**Issue by proton298** [Yepoleb/python-a2s#35]
With python-valve we had access to a function called `MasterServerQuerier()`, where we could specify the map and it would search through every server with that map. https://github.com/serverstf/python-valve#server-query-example

Is it possible with this rewrite, to also query every server that contains a certain map ? I have imported this module but there are only very few functions like `.players()` and `.info()` with the a2s module.

**Comment by Yepoleb** [comment]
The old master server protocol is deprecated and does not really work anymore. I tried implementing it a few years ago and it was impossible to use it in a way that gives consistent results. The new method is to use the Steam API, for example through this module: https://steam.readthedocs.io/en/latest/api/steam.client.builtins.html#module-steam.client.builtins.gameservers. I have never tried it though, so I can't give you any support. All I can say is the old way of doing it no longer works.
