### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by scaetano84** [Yepoleb/python-a2s#36]
Hi how are things. I would like to ask, for example, if it is possible to install it in an iptables that I use to send the attacked IPS with a range of default ports (for example, all ports of 27015:27099) then the "clean" service comes out through another interface.

Thank you.

**Comment by Yepoleb** [comment]
Sorry, I do not understand the question.

**Comment by scaetano84** [comment]
I want to send several IPs and filter on a device (where I would put python-a2s), therefore I am going to receive several /32 prefixes and I would like them to be filtered on a range of ports, such as ALL IPS (0.0.0.0) from 27015:27099

**Comment by Nereg** [comment]
Do you want to filter traffic to pass only this protocol ? There is no such functionality in this package sadly but you can easily create your own filters if you read the [specifications](https://developer.valvesoftware.com/wiki/Server_queries)
