### ISSUE TITLE
A2S_RULES not decoding correctly ?

### ISSUE THREAD

**Issue by dlartigu** [Yepoleb/python-a2s#38]
Hello and thanks a lot for the API! 
I try to get all mods on a server, for that I use the a2s_rules.
I'd like to know if it's decoded correctly ?

`import a2s`
`address = ("205.178.177.120", 2303)`
`mods = a2s.rules(address)`
`print(mods)`

->

`{'\x01\n': '\x01\x01\x01\x02\x01\x01\x01\x02gn(T"d\x7fp�\x04�H��\x15DayZ-Expansion-Quests*\x01\x03�v\x04�\x1a��\x17Chernobyl Zone Building2�l5\x04�-��\x11UndergroundBunkerp��\x04\x04�p�e\x10BaseBuilding', '\x02\n': "Plus�Q�\x01\x01\x04��\x1eb\x08CodeLock6\x14�9\x04?�m�\x08MagicBox\x16�v�\x04\x05~�l\x0fBreachingcharge\x1b�\x08E\x04��Ł\nSPBuilding�\x07�\x04q���\x11BuildingsModPack7'�\x03\x1c\x04�\x07\x06�\x1dArma", '\x03\n': ' 2 Helicopters Remastered1\x1e�(\x04dS\x19�\x17Survivalists_FacePaints��l�\x04 ���\x0eDabs Framework�ڄ\x04]�k�\x13Rearmed Server Packnm\x15\x0b\x04�<Ý\x0eTactic', '\x04\n': 'al Flava�\x03��\x04[�U�\x0fCrocos QuadbikeNc�O\x04�+\x1f�\x06ZStuff\x0b"��\x04g橎\x0fTerrain Islands�ү�\x04��8m\rFlipTransport���\x17\x04�锌\x11IndustrialModPackɖ�', '\x05\n': '\x01\x01\x04.���\x14BuildingsMegaModPack.���\x04�ޙ�\x17DayZ-Expansion-Vehicles\x1d\x0f�:\x04ȩ��\x18DayZ-Expansion-Name-Tagsvž(\x04�l��\x19DayZ-Expansion-Animati', '\x06\n': 'ons��SE\x04�\x01\x03!~\x17DayZ-Expansion-Licensed|�\x13E\x04\x16�R�\x15DayZ-Expansion-Market�x{�\x04\\ޙ�\x13DayZ-Expansion-Core����\x04T��l\rVPPAdminTools?,\x10\x01\x01\x04�', '\x07\n': "Z��\x0eMagObfuscation$�\x16\x19\x04�(��\x12DayZ Editor Loaderk\x10�]\x04_A��\x13InventoryMoveSounds�\x1c*O\x04ztM�\x07Dogtags\x18��\x01\x01\x04\x01\x02\x08'k\x12WindstrideClothing'���\x04", '\x08\n': '(��v\rMuchStuffPack�\x1a\nt\x04\x04��\\\x13Community Framework\x16\x03BBP\x0bcftoolsRoot\nCodeLockv3\x0eCrocoDocPublic\x03CZB\x04dayz\tdesignful\tExpansion\tGormirn', '\t\n': 'TI\x04HDSN\tHelkhiana\x0cInclementDab\x0bItsATreeev2\x0eJacob_Mango_V3\tJosecitox\nliquidrock\tSPModding\x06Starlv\x03VPP\tWardog.v3\x07Wayward\nWindstrid', '\n\n': 'e', 'allowedBuild': '0', 'dedicated': '1', 'island': 'Enoch', 'language': '65545', 'platform': 'win', 'requiredBuild': '0', 'requiredVersion': '119', 'timeLeft': '15'}`

Any idea on how to get the clean mods list ? :)

Thanks!

**Comment by Yepoleb** [comment]
Looks like the response has binary data mixed in with the text, because those hex values don't make sense in any of the common text encodings. You can call rules with `encoding=None` to get a binary response, but you'll still need to figure out the custom format yourself. I'd love to help you, but I currently don't have the time to look into this further.

**Comment by dlartigu** [comment]
Hello! First thanks a lot for answering me.
I've tryed the encoding=None, the only difference is I don't get any special caracters like "�".
I've tryed a hex decode lib, it's better. But still, a lot of weird stuff...

I'd like to understand that, but I don't get what's a custom format ? You mean a dedicated parsing with conversion ? Any example of what you mean, for me to know what I should look for ?
Thanks a lot! If I find a solution, I'll share it :)

**Comment by Yepoleb** [comment]
Yes, a special parser just for this game. The only info I could find was the reddit post you created. The format has to be reverse engineered, kind of like hacking, it's a lot of work.

**Comment by dlartigu** [comment]
Okay then it's what I already thought lmao ! 
I'm gonna try to parse it. Two solution: I just parse the resulted string and try to find the best way to do so. Try to parse the bytearray, but I don't even know how to do it and where to start.
Anyway, thanks a lot for your help :)

**Comment by Nereg** [comment]
You can also try other text encodings like UTF-16, different variants of UTF-8. If the server is modded mods can change output of A2S. If the server uses different language try encodings for that language (like CP855 for Cyrillic). Also it might me color coded in some way

**Comment by Yepoleb** [comment]
There is no text encoding that will decode this to readable text. Just look at `\x01\x01\x01\x02\x01\x01\x01\x02`, what word consists of 2 letters arranged like that?

**Comment by dlartigu** [comment]
Well, the thing is that I don't even know how to understand these: \x01\x01\x01\x02\x01\x01\x01\x02
Like how you know it's a word with 2 letters ?

What I can do is removing that, which lead me to something a lot more readable ->
`9GlgvNamalsk Survival`
 `                    nITvNamalsk Island`
`t\Community FrameworkdayzJacob_Mango_V3sumrak`

Then I need to figure out how to get something clean, but this already look "okay" as I get the names of the 3 mods on my server. Then I need to find a solution to get the ID of them or something.

The idea is to get at the end:
`Namalsk Survival`
`Namalsk Island`
`Community Framework`

To get this I've tryed several encodings/decoding.

> import a2s
> address = ("82.65.125.4", 28001)
> rules = a2s.rules(address, timeout=None, encoding=None)
> for keys in rules:
>     mods = rules[keys]
>     print(mods)
>     print(type(rules[keys]))
>     s = mods.decode("ascii", errors='ignore')
>     print(s)
>     break

(Sorry I don't know how to copy clean code into this post)

**Comment by dlartigu** [comment]
EDIT: You are kind of right, it's not usable with a server using a lot of mods... :/

**Comment by dlartigu** [comment]
BTW I've tryed this lib https://construct.readthedocs.io/en/latest/basics.html, but still, it's hard to get what I want!
Thanks guys for helping me

**Comment by Yepoleb** [comment]
You seem so determined to get this working, I will give it a try myself.

**Comment by Yepoleb** [comment]
I think I figured it out, I will write a module for it soon.

**Comment by Yepoleb** [comment]
There you go https://github.com/Yepoleb/dayzquery. If you can document some values please open a pull request.

**Comment by dlartigu** [comment]
Wooooo dude!! That's amazing!
Yes I'm determined when I do something haha
But, wooo that a lot. Thanks so much!

I'll see what I can do to document it :)
