### ISSUE TITLE
[Question] Multiple Query

### ISSUE THREAD

**Issue by DemOnJR** [Yepoleb/python-a2s#39]
Is possible to query 1k or more servers at once to reduce processing time, if i have an list of 10k it will take minutes to query all the servers.
If yes can i have an example?

**Comment by Nereg** [comment]
You can use async implementation of those functions and then use standard [asyncio.gather](https://docs.python.org/3/library/asyncio-task.html#running-tasks-concurrently) function to execute them in parallel. You can find [example](https://github.com/Nereg/ARKMonitorBot/blob/e8c147407d0e135300b34775fec43cebf33d095e/src/cogs/updater_cog.py#L264) in the depth of code of my discord bot you can find on my github
