### ISSUE TITLE
Rust server returning random player names instead of actual player names when using a2s.players

### ISSUE THREAD

**Issue by idevstuffs** [Yepoleb/python-a2s#41]
When using a2s.players() to query the players on a Rust server, it's returning random names or streamer mode names. I assume the server is doing this for some reason, is there a parameter that can be passed to have the server send actual player names instead of streamer mode names?

Thanks!

`Player(index=0, name='bong', score=0, duration=47998.015625)
Player(index=0, name='pete', score=0, duration=47993.86328125)
Player(index=0, name='dannie', score=0, duration=47957.96484375)
Player(index=0, name='laronda', score=0, duration=41854.796875)
Player(index=0, name='cinderella', score=0, duration=39596.9296875)
Player(index=0, name='laronda', score=0, duration=34884.58203125)
Player(index=0, name='emilio', score=0, duration=33191.6640625)
Player(index=0, name='nevada', score=0, duration=31335.51953125)
Player(index=0, name='emily', score=0, duration=29443.658203125)
Player(index=0, name='cyrstal', score=0, duration=26684.39453125)
Player(index=0, name='tommye', score=0, duration=25533.060546875)
Player(index=0, name='chanel', score=0, duration=24746.8359375)
Player(index=0, name='santiago', score=0, duration=24659.7734375)
Player(index=0, name='lou', score=0, duration=22130.740234375)
Player(index=0, name='armandina', score=0, duration=21938.16015625)
Player(index=0, name='micki', score=0, duration=20700.185546875)
Player(index=0, name='pearle', score=0, duration=20458.982421875)
Player(index=0, name='ulrike', score=0, duration=18077.22265625)
Player(index=0, name='kayce', score=0, duration=17786.447265625)
Player(index=0, name='deedra', score=0, duration=17664.4609375)
Player(index=0, name='marquetta', score=0, duration=17653.259765625)
Player(index=0, name='annamarie', score=0, duration=17591.43359375)
Player(index=0, name='rosendo', score=0, duration=17322.8125)
Player(index=0, name='marla', score=0, duration=16812.580078125)
Player(index=0, name='tai', score=0, duration=16309.318359375)
Player(index=0, name='deidre', score=0, duration=16165.7158203125)
Player(index=0, name='donnetta', score=0, duration=15291.6767578125)
Player(index=0, name='lani', score=0, duration=14520.0791015625)
Player(index=0, name='lesha', score=0, duration=14421.8759765625)
Player(index=0, name='jeana', score=0, duration=13168.6220703125)
Player(index=0, name='donnette', score=0, duration=12777.1201171875)`

**Comment by Nereg** [comment]
There could be a way of there is a way to see real names. Go to the place (Rust itself, maybe server browser) you can see real names in. Then you can use wireshark to shiff traffic the app makes and maybe there is a flag in a2s protocol that rust uses.
Currently there is no such known flag.

**Comment by Yepoleb** [comment]
I'm not aware of any parameters or even a place in the protocol where parameters could be placed. This is most likely working as intended.

**Comment by therileycloud** [comment]
It's anonymous/streamer names, rust obfuscates names and has done for the last few years.
It can be deactivated server side with this by changing this from true to false in the server.cfg: 
`server.censorplayerlist false`
