### ISSUE TITLE
S2C_CHALLENGE support?

### ISSUE THREAD

**Issue by andykais** [Yepoleb/python-a2s#42]
Hi, does this library support the experimental `S2C_CHALLENGE` challenge request? It exists to address "gameserver reflection attack vulnerability in the server browser protocol". I see code supporting `A2S_CHALLENGE_RESPONSE` [in this repo](https://github.com/Yepoleb/python-a2s/blob/master/a2s/a2s_sync.py#L15), but it also predates the announcement of the `S2C_CHALLENGE` feature, so I want to be sure if this is not a diffferent feature

https://steamcommunity.com/discussions/forum/14/2974028351344359625/

**Comment by Yepoleb** [comment]
It was implemented 3 days after the announcement in a453675feaf577dd7faa7be26281b52ac1f8a4ef

**Comment by andykais** [comment]
oh awesome thanks! Can you confirm if this same feature is supported on v1.1.4? https://github.com/Yepoleb/python-a2s/blob/v1.1.4/a2s/rules.py#L12

**Comment by Yepoleb** [comment]
Players and rule queries always had this challenge mechanism. The announcement only changed the protocol for info requests. 1.1.4 works with player and rule queries, not info, because the release predates the change.
