### ISSUE TITLE
Proposal: add A2S_PING for query server

### ISSUE THREAD

**Issue by Agnes4m** [Yepoleb/python-a2s#46]
I can use this A2S protocol on L4D2 to  [query server-related information](https://developer.valvesoftware.com/wiki/Server_queries) . `Info`, `players` and `rules` all work normally, but there is no `ping`. 

Although I know that this function is so outdated that Counter-Stroke: Source and Team Fortress 2 are not supported, I still hope to see the implementation of this function.

I also know that this is an inappropriate request. If you don't agree, close this issue

**Comment by Yepoleb** [comment]
The ping request was deprecated and replaced by timing info requests instead. Please use the `ping` value of the info response instead of a dedicated ping command.
