### ISSUE TITLE
Rust server names

### ISSUE THREAD

**Issue by MarcelMartens** [Yepoleb/python-a2s#47]
Hi! Im quite new to python aswell as network protocols so i thought i'd learn by making a small app to scrape the players on a rust server. It's going well, and reading your code aswell as some of the imports its using is getting me up to speed quicker than i thought. But i just now realized that the response im getting is the "streamer mode" names on the server (random names from a list). I've read the article on valve's dev-page and i can't find anything that would be able to change the information in the response-packet. So i thought since you've built the library maybe you have some better insight? 

Sorry if this is not the place to put this, first time interacting on GitHub aswell. if so just remove or flag it as done! :)

**Comment by Yepoleb** [comment]
Hello, welcome to Github! Your question has been asked before in issue #41. The conclusion was that the player name obfuscation is a server-side setting and can't be changed from the client. Sorry I'm not able to help with this, but good luck with your first python projects!

**Comment by MarcelMartens** [comment]
> 

Oh okay, guess i'll have to add a webscraper aswell. Thanks for the answer!
