### ISSUE TITLE
player_count

### ISSUE THREAD

**Issue by Borzoff** [Yepoleb/python-a2s#52]
Unresolved attribute reference 'player_count' for class 'Coroutine'  error if i use async method

res = a2s.ainfo(address)

**Comment by Nereg** [comment]
You forgot `await`. You should use any async methods with `await` like this:
```py
await a2s.ainfo(address)
await a2s.arules(...)
await a2s.aplayers(...)
etc...

**Comment by Borzoff** [comment]
Sorry, just noticed I didn't add await. Thanks
