### ISSUE TITLE
Request: Get MvM Mission and wave progress

### ISSUE THREAD

**Issue by Gnomesenpai** [Yepoleb/python-a2s#53]
Thanks for creating an awesome tool, would this be possible to add in? Getting the MvM Mission and wave would be really nice to be able to intergrate into other features of my community!

**Comment by Nereg** [comment]
Can you post full name (and steam id) of the game and full responses the a2s methods give you. Sadly if it isn't in on of the responses then we can't help.

**Comment by Yepoleb** [comment]
I've wanted to do this myself before but it is unfortunately not possible with this library.
