### ISSUE TITLE
ping is weird

### ISSUE THREAD

**Issue by Bluscream** [Yepoleb/python-a2s#56]
Even in your readme it shows 0.2ms ping?

**Comment by Nereg** [comment]
Please give more details. Ping is dependent on your network, and could be whatever.

**Comment by Bluscream** [comment]
Look at the ping in your example https://github.com/Yepoleb/python-a2s?tab=readme-ov-file#examples

Its clearly not meant to be 0.2ms

Also i doublechecked with the "ping" that the library returns for server far away
- ingame real ping; 111ms
- a2s reported ping: 0.01ms

**Comment by Nereg** [comment]
That is is seconds then.

**Comment by Bluscream** [comment]
You sure? a2s reports a similar number to a server running on localhost. Shouldnt tthat be actual 1ms or less?

**Comment by Nereg** [comment]
If the value is in seconds, them ms is one thousandth of a second. Just multiple that number by 1000 to get ms.

**Comment by Bluscream** [comment]
I think you misunderstood me. 
If server that's far away and has 111ms real ping shows as 0.01s
and server thats local has <1ms real ping and shows as ping = 0.03200000000651926

then something must be wrong in the ping value

**Comment by Yepoleb** [comment]
Time is in seconds as documented
> ping: float
> Round-trip delay time for the request in seconds
