### ISSUE TITLE
TypeError: Object of type SourceInfo is not JSON serializable

### ISSUE THREAD

**Issue by Bluscream** [Yepoleb/python-a2s#57]

**Comment by Nereg** [comment]
It is not, that's true. You could ither extract the needed data into a `dict` and encode that, or use python's `pickle` module, it can encode arbitrary objects: https://docs.python.org/3/library/pickle.html

**Comment by Bluscream** [comment]
The thing is, i need it specifically as a dict, so i can iterate over it and create mqtt paths from the data. I ended up changing the a2s code to use dataclasses where i need it and was able to use that to convert them to a dict but that will only work until the next update. I saw you were using your owh backport of dataclasses which doesnt actually act as dataclasses. Maybe its time to move forward and implement actual dataclasses everywhere your metaclass is used? I can PR that if you want

**Comment by Yepoleb** [comment]
A move to proper dataclasses is planned. For now you can convert the response to dict with `dict(iter(resp))`.
