### ISSUE TITLE
Is there a way to also get the user id or steamid a2s.players(address)? 

### ISSUE THREAD

**Issue by nesttle** [Yepoleb/python-a2s#8]
Is there a way to also get the user id or steamid _a2s.players(address)_?

**Comment by Yepoleb** [comment]
With a2s.players, no. You can get the server Steam ID (yes, servers have their own Steam ID) with an info query and then maybe use the Steamworks SDK too query the Steam client about the players playing on that server. I've looked into this a long time ago and that's all I remember unfortunately.
