### ISSUE TITLE
Async version of this library ?

### ISSUE THREAD

**Issue by Nereg** [Yepoleb/python-a2s#9]
Hi ! I am building bot for discord using async library so I wonderd if you can create or show me async analog of this library! Also if you nedd help to re-write some code I will help !

**Comment by Yepoleb** [comment]
I haven't written any async code yet, but I will give it a try soon.

**Comment by Nereg** [comment]
Ok ! If you nedd any help I can help you.

**Comment by InfernalPlacebo** [comment]
@Nereg what is it that you're trying to do with this that isn't working due to Async? We use this on our Discord bot just fine as is

```
server_info = ''
server_players = ''


async def server():
    global server_info
    global server_players
    try:
        server_info = a2s.info(server_address, 1.0)
        server_players = a2s.players(server_address)
        return True
    except:
        return False
```

**Comment by Yepoleb** [comment]
That's just marking a function as async without it actually being async. It still blocks waiting for a server response.

**Comment by Nereg** [comment]
It stoped my bot for a while. I am using [discord.py](https://github.com/Rapptz/discord.py) and may be it is their problem or it is my code. But I think I will rewrite this library.

**Comment by Yepoleb** [comment]
I'll give it a try as well as soon as I have time. Let's leave this open, because this is still a feature we want to have.

**Comment by iraizo** [comment]
> That's just marking a function as async without it actually being async. It still blocks waiting for a server response.

Im having the same issue right now, trying to make a bot with the library, but it just blocks the code, when the server responds it just does nothing and blocks the task, is there a way you could add a timeout parameter or something?

**Comment by Yepoleb** [comment]
Just a quick update: I am still working on this, it's just taking me way more time than expected figuring out how to properly do async UDP. But reading docs is my top priority right now and I'm committed to delivering an async implementation soon.

**Comment by iraizo** [comment]
> Just a quick update: I am still working on this, it's just taking me way more time than expected figuring out how to properly do async UDP. But reading docs is my top priority right now and I'm committed to delivering an async implementation soon.

I appreciate it

**Comment by Yepoleb** [comment]
Development branch: https://github.com/Yepoleb/python-a2s/tree/async

**Comment by Yepoleb** [comment]
Feature PR, please leave feedback if you can: https://github.com/Yepoleb/python-a2s/pull/10

**Comment by Nereg** [comment]
In fact I found code that asyncs some method. Here it is : 
```python
async def async_a2s_info(addr):
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, a2s.info, addr)
```
Found [here](https://github.com/nerakhon/conan-bot/blob/master/conan_bot/bot.py)

**Comment by Yepoleb** [comment]
Great idea to use the threading integration in asyncio to do this. The new implementation uses coroutines instead of threads though, so it scales much better, because it doesn't flood the OS with threads when mass querying.

**Comment by iraizo** [comment]
> Great idea to use the threading integration in asyncio to do this. The new implementation uses coroutines instead of threads though, so it scales much better, because it doesn't flood the OS with threads when mass querying.

Running in executor and using wait for is the perfect solution, tho it’s not really async

**Comment by Nereg** [comment]
Yeah if I will rewrite my code I will be better using not fast solution to async. And thanks you for all your support !

**Comment by Yepoleb** [comment]
Branch is now merged.
